name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: vlamdock/riskv

    steps:
    - uses: actions/checkout@v2
    - name: Pull picolibc
      run: docker exec ci_container git clone https://github.com/keith-packard/picolibc
    - name: Build picolibc
      run: |
        docker exec ci_container cd picolibc
        docker exec ci_container mkdir build
        docker exec ci_container cd build
        docker exec ci_container ../do-riscv-configure
        docker exec ci_container ninja
    - name: Initiate Tests
      run: docker exec ci_container ninja test
