name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Docker Container
      run: docker run --name ci_container docker.io/vlamdock/riskv
    - name: Pull and Build Picolibc
      run: |
        docker exec ci_container git clone https://github.com/keith-packard/picolibc
        docker exec ci_container cd picolibc
        docker exec ci_container mkdir build
        docker exec ci_container cd build
        docker exec ci_container ../do-riscv-configure
        docker exec ci_container ninja
    - name: Initiate Tests
      run: docker exec ci_container ninja test
    - name: Stop Docker Container
      run: docker stop ci_container
