name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: vlamdock/riskv

    steps:
    - uses: actions/checkout@v2
    - name: Pull picolibc
      run: git clone https://github.com/keith-packard/picolibc
    - name: Build picolibc
      run: |
        cd picolibc
        mkdir build
        cd build
        ../do-riscv-configure
        ninja
    - name: Initiate Tests
      run: ninja test
