name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: vlamdock/riskv

    steps:
    - uses: actions/checkout@v2
    - run: |
        cd picolibc
        mkdir build
        cd build
        ../do-riscv-configure
        ninja
    - name: Initiate Tests
      run: |
        cd picolibc
        cd build
        ninja test
